---
- name: Install Docker on Ubuntu 20.04
  hosts: akaylessgw.mdwlab.org 
  become: true
  become_method: sudo

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install required prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      command: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up the stable repository
      copy:
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
        dest: /etc/apt/sources.list.d/docker.list
        owner: root
        group: root
        mode: '0644'

    - name: Update the apt package index again
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

